import media from './media.json';
export const CONTACT={name:'Alejandro Henao',phone:'+1 416 825 4334',whatsapp:'14168254334',email:'alejandro@cartagena-connect.com'};
export const ORIGIN='https://vivir-segura.vercel.app';
export type Property={id:string;slug:string;name:string;type:string;location:string;city:string;price:number|null;currency:'COP'|'USD';area:number;built?:number;beds:number;baths:number;parking?:number;admin?:number;service?:boolean;levels?:number;coords?:[number,number];approx?:boolean;images:string[];story:string;storyEn:string;features:string[];featuresEn:string[];status:string;tag:string;tagEn:string;internalNotes?:string;owner?:string;commission?:number};
export const properties:Property[]=[
{id:'VS-001',slug:'finca-las-piedras-arjona',name:'Finca Las Piedras',type:'Finca',location:'Arjona · Bolívar',city:'Arjona',price:null,currency:'COP',area:10000,beds:1,baths:1,coords:[10.246295,-75.313232],images:media.finca,status:'Disponible',tag:'Naturaleza',tagEn:'Nature',story:'Una hectárea para imaginar una vida más cerca de la tierra. En la vía Las Piedras, aproximadamente a un kilómetro de la Plaza de Arjona y con acceso por vía pavimentada, esta finca reúne vegetación, una casa de una alcoba y espacios para disfrutar al aire libre. Un lugar para reunirse, cultivar y construir nuevas posibilidades.',storyEn:'One hectare to imagine a life closer to nature. On Vía Las Piedras, approximately one kilometre from Arjona’s main square, with paved-road access, this finca brings together a one-bedroom home, mature vegetation and outdoor gathering spaces.',features:['1 hectárea · aproximadamente 10.000 m²','Casa de una alcoba, sala y baño interno','Kiosco de 12 × 6 m','Piscina de 6 × 6 m','Tanque elevado · pozo artesanal con bomba','Transformador eléctrico: especificación 25 por confirmar','Habitación de cuidador · gallinero','Cancha de fútbol','7 mangos · 1 tamarindo · 1 guayabo','3 limones · 10 palmas de coco · 1 mandarina','Mamón · níspero · plátanos','Acceso por vía pavimentada'],featuresEn:['1 hectare · approximately 10,000 m²','One-bedroom house, living room and bathroom','12 × 6 m covered pavilion','6 × 6 m swimming pool','Elevated water tank · artisanal well with pump','Electrical transformer: specification 25 to be confirmed','Caretaker room · chicken coop','Football field','7 mango trees · tamarind · guava','3 lime/lemon trees · 10 coconut palms · mandarin','Mamón · loquat · plantains','Paved-road access']},
{id:'VS-002',slug:'apartamento-170-bocagrande',name:'Apartamento 170',type:'Apartamento',location:'Bocagrande · Cartagena',city:'Cartagena',price:980000000,currency:'COP',area:170,beds:3,baths:3,parking:2,admin:1394000,service:true,coords:[10.404,-75.554],approx:true,images:media.apt,status:'Disponible',tag:'Ciudad',tagEn:'City',story:'Espacio para vivir Cartagena a tu manera. Un apartamento de 170 m² en Bocagrande, con tres alcobas, tres baños y dos parqueaderos. La habitación de servicio con su propio baño aporta flexibilidad, mientras la piscina, el ascensor y la planta eléctrica completan la comodidad del edificio.',storyEn:'Space to enjoy Cartagena on your terms. A 170 m² apartment in Bocagrande with three bedrooms, three bathrooms and two parking spaces. A separate service bedroom and bathroom add flexibility, while the building offers a pool, elevator and backup generator.',features:['170 m²','3 alcobas · 3 baños','Alcoba de servicio con baño independiente','2 parqueaderos','Área social con piscina','Ascensor','Planta eléctrica','Administración: $1.394.000 COP / mes','Ubicación exacta disponible al consultar'],featuresEn:['170 m²','3 bedrooms · 3 bathrooms','Service bedroom with separate bathroom','2 parking spaces','Shared social area and swimming pool','Elevator','Backup generator','Monthly administration: COP $1,394,000','Exact location available upon inquiry']},
{id:'VS-003',slug:'casa-calle-de-la-moneda',name:'Casa Calle de la Moneda',type:'Casa',location:'Centro Histórico · Cartagena',city:'Cartagena',price:3000000,currency:'USD',area:196,built:530,beds:10,baths:12,levels:4,coords:[10.425,-75.548],approx:true,images:media.casa,status:'Disponible',tag:'Inversión',tagEn:'Investment',story:'Una propiedad con escala en el corazón del Centro Histórico. Cuatro niveles y 530 m² construidos combinan un local comercial en el primer piso, diez habitaciones con baño privado y un cuarto nivel con jacuzzi, cocina, BBQ y comedor. Su potencial comercial u hotelero está sujeto a normatividad, uso de suelo y permisos aplicables.',storyEn:'A property of scale in Cartagena’s historic centre. Four levels and 530 m² of built space combine a ground-floor commercial space, ten bedrooms with private bathrooms, and a fourth level with a jacuzzi, kitchen, BBQ and dining area. Potential commercial or hospitality use is subject to applicable regulations, land-use rules and permits.',features:['196 m² de terreno · 530 m² construidos','4 niveles','10 habitaciones, cada una con baño privado','2 baños adicionales en el cuarto nivel','Nivel 1: entrada y local comercial','Nivel 2: habitaciones y balcón hacia Calle de la Moneda','Nivel 3: habitaciones','Nivel 4: jacuzzi, cocina, BBQ, comedor y 2 baños','Uso comercial/hotelero sujeto a permisos','Número de calle y documentación por confirmar'],featuresEn:['196 m² land · 530 m² built','4 levels','10 bedrooms, each with a private bathroom','2 additional bathrooms on level four','Level 1: entrance and commercial space','Level 2: bedrooms and balcony toward Calle de la Moneda','Level 3: bedrooms','Level 4: jacuzzi, kitchen, BBQ, dining and 2 bathrooms','Commercial/hospitality use subject to permits','Street number and documents to be confirmed']}
];
export function price(p:Property,en=false){return p.price===null?(en?'Price upon request':'Precio a consultar'):(p.currency==='USD'?'US$':'$')+new Intl.NumberFormat(en?'en-US':'es-CO').format(p.price)+(p.currency==='COP'?' COP':'');}
export function whatsapp(message:string){return 'https://wa.me/'+CONTACT.whatsapp+'?text='+encodeURIComponent(message)}
export function propertyMessage(p:Property,url=ORIGIN+'/propiedades/'+p.slug){return `Hola Alejandro, me interesa ${p.id} ${p.name}. ¿Podrías enviarme más información?\n${url}`}
export function publicProperty(p:Property){const {internalNotes,owner,commission,...safe}=p;return safe}
export function parseQuery(query:string){const q=query.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');let type='';if(/apart|apartment/.test(q))type='Apartamento';else if(/finca|farm/.test(q))type='Finca';else if(/tierra|terreno|lote|land/.test(q))type='Tierra';else if(/casa|home|house/.test(q))type='Casa';else if(/inver|invest/.test(q))type='Inversión';let location='';if(q.includes('bocagrande'))location='Bocagrande';else if(/centro|historic/.test(q))location='Centro';else if(q.includes('arjona'))location='Arjona';else if(q.includes('cartagena'))location='Cartagena';const max=q.match(/(?:menos de|under|hasta|presupuesto|budget)\s*\$?\s*([\d.,]+)\s*(millones|million|mil)?/);let budget=max?Number(max[1].replace(/,/g,'.'))*(/mill/.test(max[2]||'')?1e6:max[2]==='mil'?1e3:1):0;const beds=q.match(/(\d+)\s*(?:alcobas|habitaciones|bedrooms)/);const ha=q.match(/(\d+(?:[.,]\d+)?)\s*(?:hectarea|hectare|ha\b)/);if(/cerca|near/.test(q)&&location==='Cartagena'&&(type==='Finca'||type==='Tierra'))location='';return{type,location,max:budget,beds:beds?+beds[1]:0,minArea:ha?+ha[1].replace(',','.')*10000:0,pool:/piscina|pool/.test(q)}};
